import "./globals.css";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="mt-20 ml-24 w-24  bg-lime-300">
          <Sheet>
            <SheetTrigger>Chat</SheetTrigger>
            <SheetContent>
              <SheetHeader>
                <SheetTitle>Start a chat</SheetTitle>
                <SheetDescription>
                  This will be the chat section
                </SheetDescription>
              </SheetHeader>
            </SheetContent>
          </Sheet>
        </div>
        {children}
      </body>
    </html>
  );
}
