import "./globals.css";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <div className="fixed  bottom-10  right-10">
          <Sheet>
            <SheetTrigger>
              <img className=" h-14 " src="/chat.png" alt="chat"></img>
            </SheetTrigger>
            <SheetContent>
              <SheetHeader>
                <SheetTitle>Start a chat</SheetTitle>
                <SheetDescription>
                  This will be the chat section
                </SheetDescription>
              </SheetHeader>
            </SheetContent>
          </Sheet>
        </div>
        {children}
      </body>
    </html>
  );
}
